name: Automate Paper Review

on:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  push:
    branches:
      - main

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests feedparser

    - name: Run paper fetcher
      run: python fetch_papers.py
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PATH }}

    - name: Show changes
      run: git diff papers/

    - name: Commit and push changes
      run: |
        git config --global user.name "Reyzenello"
        git config --global user.email "riccardobruzzese98@gmail.com"
        git add papers/
        git commit -m "Add new papers and review templates $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git pull --rebase
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PATH }}
